const $=s=>document.querySelector(s), main=$('#main');
const state=JSON.parse(localStorage.getItem('laddu_v3')||'{"stars":0,"done":0,"games":{},"sound":true,"lang":"hi"}');
const save=()=>{localStorage.setItem('laddu_v3',JSON.stringify(state));$('#starCount').textContent=state.stars};
const toast=t=>{const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1600)};
function speak(t){if(!state.sound||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang=/[\u0900-\u097F]/.test(t)?'hi-IN':'en-IN';u.rate=.88;speechSynthesis.speak(u)}
function reward(id){state.stars+=2;state.done++;state.games[id]=(state.games[id]||0)+1;save();tone('good');toast('बहुत बढ़िया! ⭐ +2')}
function tone(kind='good'){if(!state.sound)return;const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=kind==='good'?660:220;g.gain.value=.035;o.start();o.stop(c.currentTime+.12)}
const skills=['Critical thinking','Creativity','Communication','Collaboration','Problem solving','Digital literacy','Information literacy','Adaptability','Initiative','Leadership','Social-emotional learning','Productivity & self-management'];
const domains=['Physical Development','Socio-emotional & Ethical Development','Cognitive Development','Language & Literacy','Aesthetic & Cultural Development','Positive Learning Habits'];
const games=[
{id:'abc',icon:'🔤',title:'ABC Detective',desc:'Letters, sounds, beginning sounds & playful clues',tag:'LANGUAGE'},
{id:'hindi',icon:'अ',title:'अक्षर मेला',desc:'स्वर, व्यंजन, ध्वनि, चित्र और शब्द पहचान',tag:'हिंदी'},
{id:'count',icon:'🔢',title:'1–100 Number Safari',desc:'Counting, quantity, sequence, comparison & patterns',tag:'MATH'},
{id:'story',icon:'🔎',title:'Mystery Story Quest',desc:'Funny family mysteries, clues, prediction & sequencing',tag:'STORY'},
{id:'craft',icon:'🎨',title:'DIY Create Lab',desc:'Draw, design, classify, plan and make',tag:'ART'},
{id:'music',icon:'🎵',title:'Birthday Music & Dance',desc:'Rhythm, rhyme, beat, movement & listening',tag:'MUSIC'},
{id:'family',icon:'🏠',title:'Family Helper',desc:'Everyday choices, empathy, safety & responsibility',tag:'LIFE'},
{id:'prank',icon:'😂',title:'Funny Prank Fixer',desc:'Harmless comedy choices, cause-effect & social thinking',tag:'COMEDY'},
{id:'memory',icon:'🧠',title:'Memory Detective',desc:'Attention, working memory, matching and recall',tag:'BRAIN'},
{id:'sort',icon:'🧺',title:'Sort & Solve',desc:'Colours, shapes, sizes, attributes and reasoning',tag:'COGNITION'},
{id:'sequence',icon:'🧩',title:'What Comes Next?',desc:'Patterns, stories, routines and logical sequencing',tag:'LOGIC'},
{id:'rhymes',icon:'🎶',title:'Rhyme & Action Room',desc:'Rhymes, phonological awareness and movement',tag:'RHYME'},
{id:'nature',icon:'🌱',title:'Little Nature Explorer',desc:'Observation, living/non-living, care and curiosity',tag:'EVS'},
{id:'feelings',icon:'💛',title:'Feelings & Friendship',desc:'Emotion recognition, choices, kindness and cooperation',tag:'SEL'},
{id:'body',icon:'🤸',title:'Move & Balance',desc:'Gross motor prompts, left/right, rhythm and coordination',tag:'PHYSICAL'},
{id:'market',icon:'🛒',title:'Mini Market',desc:'Counting, money-like quantity, choices and communication',tag:'LIFE MATH'},
{id:'sound',icon:'👂',title:'Sound Detective',desc:'Listen, distinguish, repeat and connect sound to meaning',tag:'AUDIO'},
{id:'open',icon:'✨',title:'Open Play Studio',desc:'Choose your own goal and combine story, art, music & math',tag:'FREE PLAY'}];
function home(){main.innerHTML=`<section class="screen"><div class="hero"><div><div class="eyebrow">Laddu Learning World</div><h1>खेलते-खेलते<br>सीखो, बनाओ, सोचो।</h1><p>एक interest-led play world जहाँ <b>comedy, family/vlog, kids/cartoon, story–mystery–fantasy, DIY/drawing और music/dance</b> interests learning activities का engine हैं।</p><div class="hero-actions"><button class="primary" id="start">🎮 आज का Play Path</button><button class="secondary" id="all">🧭 सभी Activities</button></div></div><div class="real-scene"><div class="kid"></div><div class="scene-toy">🎨</div><div style="position:absolute;right:8%;top:10%;font-size:48px">☀️</div></div></div><div class="stats"><div class="stat"><b>${state.stars}</b><span>Learning stars</span></div><div class="stat"><b>${state.done}</b><span>Completed rounds</span></div><div class="stat"><b>100</b><span>Counting target</span></div><div class="stat"><b>6</b><span>Foundation domains</span></div></div><div class="section-head"><div><h2>🎯 Interest-led Play Library</h2><p>हर activity में enjoyment + learning objective साथ चलता है।</p></div></div><div class="game-grid">${games.map(g=>`<article class="game-card" data-game="${g.id}"><div class="scene"><span>${g.icon}</span><span class="tag">${g.tag}</span></div><h3>${g.title}</h3><p>${g.desc}</p></article>`).join('')}</div><div class="section-head"><div><h2>🧠 12 Future Skills</h2><p>इन skills की repeated practice activities में woven है।</p></div></div><div class="skills">${skills.map(s=>`<span class="skill">${s}</span>`).join('')}</div><div class="section-head"><div><h2>🌱 Foundation Stage Coverage</h2><p>NCF-FS के broad developmental domains को activity design में integrate किया गया है।</p></div></div><div class="skills">${domains.map(s=>`<span class="skill">${s}</span>`).join('')}</div></section>`;$('#start').onclick=()=>playPath();$('#all').onclick=()=>window.scrollTo({top:430,behavior:'smooth'});document.querySelectorAll('[data-game]').forEach(x=>x.onclick=()=>launch(x.dataset.game))}
function head(title,sub){return `<div class="game-head"><button class="back" onclick="home()">← Home</button><div><h1>${title}</h1><small>${sub}</small></div></div>`}
function launch(id){const f={abc,hindi,count,story,craft,music,family,prank,memory,sort,sequence,rhymes,nature,feelings,body,market,sound,open}[id];if(f)f()}
function qGame(id,title,sub,prompt,items,answer,explain){let done=false;main.innerHTML=`<section class="screen play-shell">${head(title,sub)}<div class="game-area"><div class="objective">🎯 ${explain}</div><div class="prompt">${prompt}</div><div class="choices">${items.map((x,i)=>`<button class="choice" data-i="${i}">${x}</button>`).join('')}</div><div id="fb" class="feedback"></div></div></section>`;document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{if(done)return;const ok=+b.dataset.i===answer;if(ok){done=true;$('#fb').textContent='सही! तुम्हारी thinking बहुत बढ़िया है। ⭐';speak('बहुत बढ़िया!');reward(id)}else{$('#fb').textContent='अच्छी कोशिश! Clue फिर देखो और एक बार और सोचो।';tone('bad')}})}
function abc(){const letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');const data={A:['🍎','Apple'],B:['🎈','Balloon'],C:['🐱','Cat'],D:['🐶','Dog'],E:['🥚','Egg'],F:['🐟','Fish'],G:['🍇','Grapes'],H:['🏠','House'],I:['🍦','Ice cream'],J:['🧃','Juice'],K:['🪁','Kite'],L:['🦁','Lion'],M:['🥭','Mango'],N:['👃','Nose'],O:['🍊','Orange'],P:['🦜','Parrot'],Q:['👑','Queen'],R:['🌈','Rainbow'],S:['☀️','Sun'],T:['🐯','Tiger'],U:['☂️','Umbrella'],V:['🚐','Van'],W:['🍉','Watermelon'],X:['🎼','Xylophone'],Y:['🪀','Yo-yo'],Z:['🦓','Zebra']};main.innerHTML=`<section class="screen">${head('ABC Detective','Tap a letter → hear it → find the beginning sound')}<div class="game-area"><div class="objective">🔤 Letter recognition, sound-symbol connection, vocabulary and oral language.</div><div class="abc-grid">${letters.map(l=>`<button class="letter-btn" data-l="${l}">${l}<small>${data[l][1]}</small></button>`).join('')}</div><div id="abcPlay" class="empty">एक letter चुनो। फिर clue के साथ sound बोलो।</div></div></section>`;document.querySelectorAll('.letter-btn').forEach(b=>b.onclick=()=>{const l=b.dataset.l,[e,w]=data[l];$('#abcPlay').innerHTML=`<div class="prompt">${l} → ${e}</div><p class="sub"><b>${w}</b> — बोलो: “${l} for ${w}”</p><button class="primary" id="abcSpeak">🔊 सुनो और बोलो</button>`;speak(`${l} for ${w}`);$('#abcSpeak').onclick=()=>{speak(`${l} for ${w}`);reward('abc')}})}
function hindi(){const a=[['अ','अनार'],['आ','आम'],['इ','इमली'],['ई','ईख'],['उ','उल्लू'],['ऊ','ऊन'],['ए','एड़ी'],['ऐ','ऐनक'],['ओ','ओखली'],['औ','औरत'],['अं','अंगूर'],['क','कमल'],['ख','खरगोश'],['ग','गमला'],['घ','घर'],['च','चम्मच'],['छ','छाता'],['ज','जहाज'],['झ','झंडा'],['ट','टमाटर'],['ठ','ठेला'],['ड','डमरू'],['ढ','ढक्कन'],['त','तरबूज'],['थ','थाली'],['द','दरवाज़ा'],['ध','धनुष'],['न','नल'],['प','पतंग'],['फ','फल'],['ब','बतख'],['भ','भालू'],['म','मछली'],['य','योग'],['र','रथ'],['ल','लड्डू'],['व','वन'],['श','शेर'],['ष','षट्कोण'],['स','सूरज'],['ह','हाथी']];main.innerHTML=`<section class="screen">${head('अक्षर मेला','स्वर + व्यंजन • ध्वनि • चित्र/शब्द • बोलने का अभ्यास')}<div class="game-area"><div class="objective">🗣️ सुनना, बोलना, अक्षर पहचानना और ध्वनि को अर्थपूर्ण शब्द से जोड़ना।</div><div class="hindi-grid">${a.map(([l,w])=>`<button class="letter-btn" data-l="${l}">${l}<small>${w}</small></button>`).join('')}</div><div id="hiPlay" class="empty">कोई अक्षर चुनो।</div></div></section>`;document.querySelectorAll('.hindi-grid .letter-btn').forEach(b=>b.onclick=()=>{const [l,w]=a.find(x=>x[0]===b.dataset.l);$('#hiPlay').innerHTML=`<div class="prompt">${l} → ${w}</div><p class="sub">बोलो: “${l} से ${w}”</p><button class="primary" id="hiSpeak">🔊 सुनो</button>`;speak(`${l} से ${w}`);$('#hiSpeak').onclick=()=>{speak(`${l} से ${w}`);reward('hindi')}})}
function count(){main.innerHTML=`<section class="screen">${head('1–100 Number Safari','Count, compare, sequence, patterns and quantity')}<div class="game-area"><div class="objective">🔢 Stable counting 1–100, one-to-one correspondence, quantity, before/after, more/less and simple patterns.</div><div class="num-grid">${Array.from({length:100},(_,i)=>`<button class="num-btn" data-n="${i+1}">${i+1}<small>tap</small></button>`).join('')}</div><div class="count-stage"><div id="countPrompt" class="prompt">कोई number चुनो</div><div id="countItems" class="count-items"></div><div id="countFb" class="feedback"></div></div></div></section>`;document.querySelectorAll('.num-btn').forEach(b=>b.onclick=()=>{const n=+b.dataset.n;$('#countPrompt').innerHTML=`${n}<br><small>अब ${n} तक count करो</small>`;const lim=Math.min(n,40);$('#countItems').innerHTML=Array.from({length:lim},(_,i)=>`<span class="object">${['🍎','⭐','🎈','🧸','🌸'][i%5]}</span>`).join('')+(n>40?`<span class="sub">+ ${n-40} more — groups में mentally count करो</span>`:'');$('#countFb').innerHTML=`<button class="secondary" id="countHear">🔊 ${n} को सुनो</button> <button class="primary" id="countChallenge">🎯 Quick Challenge</button>`;$('#countHear').onclick=()=>speak(String(n));$('#countChallenge').onclick=()=>qGame('count','Number Safari Challenge','Counting & comparison',`कौन-सा number ${n} के बाद आता है?`,[String(Math.max(1,n-1)),String(n),String(Math.min(100,n+1)),String(Math.min(100,n+2))],2,'Sequence और before/after समझना।')})}
function story(){const qs=[['🔎','Birthday Box Mystery','घर में birthday box मिला। पहले क्या करना सबसे sensible है?',['अंदर बिना पूछे हाथ डालना','Clue देखना और परिवार से पूछना','भाग जाना','सब चीजें छिपा देना'],1],['🧩','Three Clues','एक toy shelf पर नहीं है। clue कहता है: “जहाँ books रहती हैं।” कहाँ खोजोगे?',['Kitchen','Bathroom','Bookshelf','Garden'],2],['👻','Friendly Mystery','रात को खिड़की से आवाज़ आई। safe first step क्या है?',['अकेले बाहर जाना','किसी trusted adult को बताना','खिड़की तोड़ना','चिल्लाकर दौड़ना'],1]];let i=0;const render=()=>{const q=qs[i];main.innerHTML=`<section class="screen">${head('Mystery Story Quest','Fantasy + mystery + safe problem solving')}<div class="game-area"><div class="story"><div class="clue">${q[0]}</div><h2>${q[1]}</h2><p>Story clue पढ़ो/सुनो, सोचो और safest smart choice चुनो।</p><div class="story-actions"><button class="secondary" id="storyHear">🔊 सुनो</button></div></div><div class="choices">${q[3].map((x,j)=>`<button class="choice" data-i="${j}">${x}</button>`).join('')}</div><div id="fb" class="feedback"></div></div></section>`;$('#storyHear').onclick=()=>speak(q[2]);document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{if(+b.dataset.i===q[4]){reward('story');i++;if(i<qs.length)setTimeout(render,450);else toast('Mystery solved! 🕵️ ⭐')}else{$('#fb').textContent='Clue फिर पढ़ो और सोचो।';tone('bad')}})};render()}
function craft(){main.innerHTML=`<section class="screen">${head('DIY Create Lab','Drawing • planning • making • explaining')}<div class="game-area"><div class="objective">🎨 Fine-motor control, visual expression, planning, creativity, vocabulary and reflection.</div><div class="craft-board"><div class="craft-card" id="draw"><div class="big">✏️</div><h2>Free Drawing</h2><p>Theme: “Funny family picnic”. Draw it and explain 3 things.</p></div><div class="craft-card" id="trace"><div class="big">🔤</div><h2>Trace & Decorate</h2><p>ABC या हिंदी अक्षर चुनो, फिर related objects draw करो।</p></div><div class="craft-card" id="sortcraft"><div class="big">♻️</div><h2>Build from Things</h2><p>Paper, box, spoon, cup जैसी safe household चीज़ों से imaginary toy plan करो।</p></div><div class="craft-card" id="patterncraft"><div class="big">🟡🔵</div><h2>Pattern Maker</h2><p>Colour/shape pattern बनाओ और बताओ next क्या आएगा।</p></div></div></div></section>`;$('#draw').onclick=()=>drawing();$('#trace').onclick=()=>trace();$('#sortcraft').onclick=()=>qGame('craft','DIY Plan','Creativity + planning','Toy बनाने से पहले सबसे अच्छा पहला step क्या है?',['Plan/draw the idea','Randomly cut everything','Hide the materials','Ask nobody'],0,'Planning, initiative and problem solving.');$('#patterncraft').onclick=()=>qGame('craft','Pattern Maker','Math + creativity','🟡 🔵 🟡 🔵 — next?',['🟡','🔵','🟢','🔴'],0,'Recognising and extending patterns.')}
function drawing(){main.innerHTML=`<section class="screen">${head('Free Drawing Studio','Draw → create → explain')}<div class="game-area"><div class="draw-wrap"><p class="prompt">Funny Family Picnic 🍉</p><canvas class="draw-canvas" id="canvas"></canvas><div class="draw-tools"><button class="primary" id="clear">Clear</button> <button class="secondary" id="doneDraw">I’m Done ⭐</button></div></div></div></section>`;const c=$('#canvas'),ctx=c.getContext('2d');const r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;ctx.scale(d,d);ctx.lineWidth=4;ctx.lineCap='round';let down=false,last=null;c.onpointerdown=e=>{down=true;last=[e.offsetX,e.offsetY]};c.onpointermove=e=>{if(!down)return;ctx.beginPath();ctx.moveTo(...last);ctx.lineTo(e.offsetX,e.offsetY);ctx.stroke();last=[e.offsetX,e.offsetY]};window.onpointerup=()=>down=false;$('#clear').onclick=()=>ctx.clearRect(0,0,c.width,c.height);$('#doneDraw').onclick=()=>reward('craft')}
function trace(){const letters=['A','B','C','D','अ','आ','क','ख','ग','म','ल'];let i=0;main.innerHTML=`<section class="screen">${head('Trace & Decorate','Pre-writing + letter formation')}<div class="game-area"><div class="trace-board"><div class="prompt" id="tr">${letters[i]}</div><p class="sub">Finger से हवा में/कागज़ पर shape trace करो। फिर बोलो।</p><div class="next-row"><button class="secondary" id="prev">←</button> <button class="primary" id="speakTr">🔊 बोलो</button> <button class="secondary" id="next">→</button></div></div></div></section>`;$('#prev').onclick=()=>{i=(i+letters.length-1)%letters.length;$('#tr').textContent=letters[i]};$('#next').onclick=()=>{i=(i+1)%letters.length;$('#tr').textContent=letters[i]};$('#speakTr').onclick=()=>{speak(letters[i]);reward('craft')}}
function music(){const notes=['Do','Re','Mi','Fa','Sol','La','Ti','Do'];main.innerHTML=`<section class="screen">${head('Birthday Music & Dance','Rhythm • listening • memory • joyful movement')}<div class="game-area"><div class="objective">🎵 Beat awareness, auditory discrimination, memory, coordination, self-expression and confidence.</div><div class="music-pad">${notes.map((n,i)=>`<button class="pad" data-i="${i}">${n}<small>${i+1}</small></button>`).join('')}</div><div class="dance" style="margin-top:18px"><div><div id="dc" class="dance-character">🧒🎂</div><p>Tap a beat, then copy the 3-beat pattern.</p><button class="primary" id="danceBtn">💃 Start Dance</button></div></div></div></section>`;document.querySelectorAll('.pad').forEach(b=>b.onclick=()=>{tone('good');speak(b.textContent.replace(/\d/g,''))});$('#danceBtn').onclick=()=>{$('#dc').classList.toggle('active');reward('music')}}
function family(){qGame('family','Family Helper','Family/vlog-style real-life play','दादी/मम्मी busy हैं। घर में मदद का अच्छा तरीका क्या है?',['उनका काम और कठिन बनाना','पूछकर छोटा safe काम करना','बिना बताए चीज़ें छिपाना','मदद करने से मना करना'],1,'Empathy, communication, responsibility and initiative.')}
function prank(){qGame('prank','Funny Prank Fixer','Comedy without hurting anyone','दोस्त को funny surprise देना है। कौन-सा idea respectful है?',['उसकी चीज़ छिपा देना','डराने वाला prank','Funny drawing/card बनाना','उसका secret बताना'],2,'Comedy को kindness, consent and social awareness से जोड़ना।')}
function memory(){const items=['🍎','🐶','🎈','🧸','🌈','🍰'];let seq=[...items].sort(()=>Math.random()-.5).slice(0,4);main.innerHTML=`<section class="screen">${head('Memory Detective','Look • remember • recall')}<div class="game-area"><div id="memoryPrompt" class="prompt">${seq.join(' ')}</div><p class="sub">5 seconds देखो… फिर order याद करो!</p><button class="primary" id="hide">Hide & Test</button><div id="mem" class="empty"></div></div></section>`;$('#hide').onclick=()=>{$('#memoryPrompt').textContent='?  ?  ?  ?';$('#mem').innerHTML=items.map(x=>`<button class="choice" data-x="${x}">${x}</button>`).join('');document.querySelectorAll('#mem .choice').forEach(b=>b.onclick=()=>{const ok=b.dataset.x===seq[0];if(ok){seq.shift();b.disabled=true;if(!seq.length){reward('memory');$('#mem').textContent='पूरा sequence याद रखा!'}}else{tone('bad');toast('फिर से clue याद करो 🙂')}})}}
function sort(){const sets=[['बड़ा क्या है?',['🐘','🐜','🐭','🐱'],0],['कौन अलग है?',['🍎','🍌','🥭','🚗'],3],['कौन living है?',['🌳','🪑','⚽','कप'],0]];const q=sets[Math.floor(Math.random()*sets.length)];qGame('sort','Sort & Solve','Attributes + reasoning',q[0],q[1],q[2],'Compare attributes and explain your choice.')}
function sequence(){qGame('sequence','What Comes Next?','Patterns + routines','🌞 → 🛁 → 👕 → ?',['🍽️','🌙','🏫','🌧️'],0,'Everyday routine sequencing and reasoning.')}
function rhymes(){const q=[['Twinkle, twinkle, little star','⭐','Which word rhymes with “star”?',['car','dog','sun','book'],0],['Happy Birthday to you','🎂','Birthday song में किसके लिए हम celebrate करते हैं?',['A birthday','A rainy day','A shoe','A pencil'],0],['आओ नाचें, ताल मिलाएँ','🥁','Beat follow करने का best तरीका?',['ध्यान से सुनो और copy करो','आँखें बंद करके भागो','दूसरों को धक्का दो','संगीत रोक दो'],0]][Math.floor(Math.random()*3)];qGame('rhymes','Rhyme & Action Room','Rhymes + phonological awareness + movement',q[2],q[3],q[4],'Listen, rhyme, respond and move with rhythm.')}
function nature(){qGame('nature','Little Nature Explorer','Observation + care','पौधे को healthy रखने के लिए क्या कर सकते हैं?',['उसे पानी देना','उसे तोड़ना','कचरा डालना','उसकी मिट्टी हटाना'],0,'Observation, care for living things and responsibility.')}
function feelings(){qGame('feelings','Feelings & Friendship','Socio-emotional learning','दोस्त का tower गिर गया और वह sad है। helpful response?',['हँसना','पूछना: “मैं मदद करूँ?”','उसका tower और गिराना','भाग जाना'],1,'Emotion recognition, empathy, communication and cooperation.')}
function body(){main.innerHTML=`<section class="screen">${head('Move & Balance','Gross motor • coordination • rhythm')}<div class="game-area"><div class="dance"><div><div id="dc" class="dance-character">🧒</div><p class="prompt">Coach says…</p><p>“Jump 3 times → clap 2 times → turn left.”</p><button class="primary" id="go">▶ Start</button></div></div></div></section>`;$('#go').onclick=()=>{$('#dc').classList.add('active');setTimeout(()=>{$('#dc').classList.remove('active');reward('body')},1800)}}
function market(){qGame('market','Mini Market','Counting + communication','तुम्हारे पास 5 apples हैं। 2 दे दिए। कितने बचे?',['2','3','4','5'],1,'Quantity, subtraction intuition, communication and everyday math.')}
function sound(){const qs=[['🐶','कौन-सी आवाज़ dog से जुड़ी है?',['meow','woof','moo','quack'],1],['🐱','कौन-सी आवाज़ cat से जुड़ी है?',['meow','roar','woof','neigh'],0],['🐮','कौन-सी आवाज़ cow से जुड़ी है?',['quack','moo','meow','chirp'],1]];const q=qs[Math.floor(Math.random()*qs.length)];qGame('sound','Sound Detective','Listening + language',q[1],q[2],q[3],'Listen carefully and connect sound to meaning.')}
function open(){main.innerHTML=`<section class="screen">${head('Open Play Studio','Child choice • guided discovery • integrated learning')}<div class="game-area"><div class="objective">✨ Choose any 2 interests and make your own mini-adventure. This supports agency, initiative and positive learning habits.</div><div class="choices">${games.slice(0,8).map(g=>`<button class="choice" data-id="${g.id}">${g.icon}<small>${g.title}</small></button>`).join('')}</div><div class="empty">Pick two, then play them in any order. No “wrong” creative path.</div></div></section>`;let picked=[];document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{picked.push(b.dataset.id);b.disabled=true;if(picked.length===2){reward('open');setTimeout(()=>launch(picked[0]),400)}})}
function playPath(){const path=['abc','hindi','count','story','craft','music','family','prank','memory','sort','sequence','rhymes','nature','feelings','body','market','sound','open'];launch(path[state.done%path.length])}
$('#homeBtn').onclick=home;$('#soundBtn').onclick=()=>{state.sound=!state.sound;save();$('#soundBtn').textContent=state.sound?'🔊 Sound':'🔇 Muted'};$('#langBtn').onclick=()=>{state.lang=state.lang==='hi'?'en':'hi';save();toast(state.lang==='hi'?'हिंदी mode':'English mode')};save();home();