const $=s=>document.querySelector(s),main=$('#main');
const state=JSON.parse(localStorage.getItem('laddu_v4')||'{"stars":0,"done":0,"sound":true}');
const save=()=>{localStorage.setItem('laddu_v4',JSON.stringify(state));const e=$('#starCount');if(e)e.textContent=state.stars};
const toast=t=>{const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>e.classList.remove('show'),1500)};
let AC=null;
function audio(){if(!state.sound)return null;const C=window.AudioContext||window.webkitAudioContext;if(!C)return null;if(!AC)AC=new C();if(AC.state==='suspended')AC.resume();return AC}
function sfx(type='tap'){const c=audio();if(!c)return;const now=c.currentTime;const gain=c.createGain();gain.connect(c.destination);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.055,now+.015);gain.gain.exponentialRampToValueAtTime(.0001,now+.22);const o=c.createOscillator();o.connect(gain);const cfg={tap:[520,0],success:[660,330],wrong:[180,0],pop:[300,650],magic:[440,880],horror:[90,55],craft:[240,420],dance:[330,495],count:[260,390],whoosh:[700,180]}[type]||[520,0];o.frequency.setValueAtTime(cfg[0],now);if(cfg[1])o.frequency.exponentialRampToValueAtTime(cfg[1],now+.2);o.type=type==='horror'?'sawtooth':type==='magic'?'sine':'triangle';o.start(now);o.stop(now+.23);if(type==='horror'){const n=c.createOscillator(),g=c.createGain();n.type='sawtooth';n.frequency.value=43;n.connect(g);g.connect(c.destination);g.gain.setValueAtTime(.018,now);g.gain.exponentialRampToValueAtTime(.0001,now+.45);n.start(now);n.stop(now+.46)}}
function speak(t){if(!state.sound||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang=/[\u0900-\u097F]/.test(t)?'hi-IN':'en-IN';u.rate=.86;speechSynthesis.speak(u)}
function reward(id){state.stars+=2;state.done++;save();sfx('success');toast('बहुत बढ़िया! ⭐ +2');}
const skills=['Critical Thinking','Creativity','Communication','Collaboration','Problem Solving','Digital Literacy','Information Literacy','Adaptability','Initiative','Leadership','Social-Emotional Learning','Self-management'];
const domains=['Physical Development','Socio-emotional & Ethical Development','Cognitive Development','Language & Literacy','Aesthetic & Cultural Development','Positive Learning Habits'];
const games=[
['abc','🔤','ABC Detective','Comedy clues + beginning sounds','LANGUAGE'],['hindi','अ','अक्षर मेला','चित्र, ध्वनि और Hindi अक्षर','भाषा'],['count','🔢','Number Safari 1–100','Count, compare, sequence & patterns','MATH'],['story','🔎','Mystery Mansion','Funny-safe mystery, clues & prediction','STORY'],['craft','🎨','DIY Drawing Studio','Trace, draw, design and create','ART'],['music','🎵','Birthday Beat Party','Rhymes, rhythm, listening & dance','MUSIC'],['family','🏠','Family Vlog Day','Routines, empathy, choices & sequencing','FAMILY'],['prank','😂','Prank Detective','Harmless funny cause-and-effect choices','COMEDY'],['memory','🧠','Memory Snap','Attention, working memory & recall','BRAIN'],['sort','🧺','Toy Sorting Challenge','Classify by attributes and explain why','LOGIC'],['sequence','🧩','Story Sequence','Put events in logical order','LOGIC'],['rhymes','🎶','Rhyme & Action','Sound play, rhyme and movement','RHYME'],['nature','🌱','Nature Explorer','Observe, compare and care','EVS'],['feelings','💛','Friendship Choices','Feelings, empathy and cooperation','SEL'],['body','🤸','Move Like a Character','Balance, direction and coordination','PHYSICAL'],['market','🛒','Mini Family Market','Quantity, counting and communication','LIFE MATH'],['sound','👂','Sound Detective','Listen, identify and imitate','AUDIO'],['open','✨','Free Play Studio','Combine story, art, music & maths','OPEN']];
function head(t,s){return `<div class="game-head"><button class="back" id="back">← Home</button><div><h1>${t}</h1><small>${s}</small></div></div>`}
function home(){main.innerHTML=`<section class="screen"><div class="hero"><div><div class="eyebrow">Laddu • Interest-led Learning</div><h1>खेलो। हँसो।<br>सोचो। बनाओ।</h1><p>तुम्हारी बच्ची के <b>Comedy, Family, Kids/Cartoon, Story-Mystery-Fantasy, DIY/Drawing और Music/Dance</b> interests को learning engine बनाया गया है। हर tap का feedback, हर world की अपनी sound language, और हर activity में foundational learning.</p><div class="hero-actions"><button class="primary" id="start">🎮 आज का Play Path</button><button class="secondary" id="soundTest">🔊 Sound Lab</button></div></div><div class="real-scene"><div class="kid"></div><div class="scene-toy">🎨</div></div></div><div class="stats"><div class="stat"><b>${state.stars}</b><span>Learning stars</span></div><div class="stat"><b>${state.done}</b><span>Completed rounds</span></div><div class="stat"><b>1–100</b><span>Counting range</span></div><div class="stat"><b>6</b><span>NCF-FS domains</span></div></div><div class="section-head"><div><h2>🎯 Her Interest → Learning</h2><p>हर card एक अलग play universe है।</p></div></div><div class="game-grid">${games.map(g=>`<article class="game-card" data-game="${g[0]}"><div class="scene">${g[1]}<span class="tag">${g[4]}</span></div><h3>${g[2]}</h3><p>${g[3]}</p></article>`).join('')}</div><div class="section-head"><div><h2>🧠 12 Future Skills</h2><p>Activities में naturally woven practice.</p></div></div><div class="skills">${skills.map(x=>`<span class="skill">${x}</span>`).join('')}</div><div class="section-head"><div><h2>🌱 Foundation Stage</h2><p>Six broad developmental domains.</p></div></div><div class="skills">${domains.map(x=>`<span class="skill">${x}</span>`).join('')}</div></section>`;$('#start').onclick=()=>playPath();$('#soundTest').onclick=()=>{sfx('magic');toast('🔊 Sound world ready')};document.querySelectorAll('[data-game]').forEach(e=>e.onclick=()=>launch(e.dataset.game));save()}
function bindBack(){const b=$('#back');if(b)b.onclick=home}
function launch(id){sfx('whoosh');({abc,hindi,count,story,craft,music,family,prank,memory,sort,sequence,rhymes,nature,feelings,body,market,sound,open}[id]||home)();}
function qGame(id,title,sub,prompt,items,ans,objective,kind='tap'){let locked=false;main.innerHTML=`<section class="screen play-shell">${head(title,sub)}<div class="game-area"><div class="objective">🎯 ${objective}</div><div class="prompt">${prompt}</div><div class="choices">${items.map((x,i)=>`<button class="choice" data-i="${i}">${x}</button>`).join('')}</div><div id="fb" class="feedback"></div></div></section>`;bindBack();document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{if(locked)return;sfx(kind);if(+b.dataset.i===ans){locked=true;$('#fb').textContent='सही! तुमने clue को ध्यान से देखा। ⭐';reward(id)}else{$('#fb').textContent='फिर से सोचो — कोई जल्दी नहीं 😊';sfx('wrong')}})}
function abc(){const d={A:['🍎','Apple'],B:['🎈','Balloon'],C:['🐱','Cat'],D:['🐶','Dog'],E:['🥚','Egg'],F:['🐟','Fish'],G:['🍇','Grapes'],H:['🏠','House'],I:['🍦','Ice cream'],J:['🧃','Juice'],K:['🪁','Kite'],L:['🦁','Lion'],M:['🥭','Mango'],N:['👃','Nose'],O:['🍊','Orange'],P:['🦜','Parrot'],Q:['👑','Queen'],R:['🌈','Rainbow'],S:['☀️','Sun'],T:['🐯','Tiger'],U:['☂️','Umbrella'],V:['🚐','Van'],W:['🍉','Watermelon'],X:['🎼','Xylophone'],Y:['🪀','Yo-yo'],Z:['🦓','Zebra']};main.innerHTML=`<section class="screen">${head('ABC Detective','Funny clues • sound • vocabulary')}<div class="game-area"><div class="objective">🔤 A–Z recognition, phonological awareness, vocabulary, listening and oral language.</div><div class="abc-grid">${Object.keys(d).map(l=>`<button class="letter-btn" data-l="${l}">${l}<small>${d[l][1]}</small></button>`).join('')}</div><div id="abcPlay" class="empty">कोई letter चुनो — फिर बोलो!</div></div></section>`;bindBack();document.querySelectorAll('.letter-btn').forEach(b=>b.onclick=()=>{const l=b.dataset.l,[e,w]=d[l];sfx('tap');$('#abcPlay').innerHTML=`<div class="prompt">${l} → ${e}</div><p class="sub"><b>${w}</b><br>“${l} for ${w}”</p><button class="primary" id="say">🔊 सुनो और बोलो</button>`;speak(`${l} for ${w}`);$('#say').onclick=()=>{speak(`${l} for ${w}`);reward('abc')}})}
function hindi(){const a=['अ','आ','इ','ई','उ','ऊ','ए','ऐ','ओ','औ','अं','क','ख','ग','घ','च','छ','ज','झ','ट','ठ','ड','ढ','त','थ','द','ध','न','प','फ','ब','भ','म','य','र','ल','व','श','ष','स','ह'],w=['अनार','आम','इमली','ईख','उल्लू','ऊन','एड़ी','ऐनक','ओखली','औरत','अंगूर','कमल','खरगोश','गमला','घर','चम्मच','छाता','जहाज','झंडा','टमाटर','ठेला','डमरू','ढक्कन','तरबूज','थाली','दरवाज़ा','धनुष','नल','पतंग','फल','बतख','भालू','मछली','योग','रथ','लड्डू','वन','शेर','षट्कोण','सूरज','हाथी'];main.innerHTML=`<section class="screen">${head('अक्षर मेला','स्वर + व्यंजन • picture-word connection')}<div class="game-area"><div class="objective">🇮🇳 अक्षर पहचान, ध्वनि, शब्द-संबंध, सुनना और बोलना।</div><div class="hindi-grid">${a.map((x,i)=>`<button class="letter-btn" data-i="${i}">${x}<small>${w[i]}</small></button>`).join('')}</div><div id="hiPlay" class="empty">अक्षर चुनो।</div></div></section>`;bindBack();document.querySelectorAll('.hindi-grid .letter-btn').forEach(b=>b.onclick=()=>{const i=+b.dataset.i;sfx('tap');$('#hiPlay').innerHTML=`<div class="prompt">${a[i]} → ${w[i]}</div><button class="primary" id="hisay">🔊 ${a[i]} से ${w[i]}</button>`;speak(`${a[i]} से ${w[i]}`);$('#hisay').onclick=()=>{speak(`${a[i]} से ${w[i]}`);reward('hindi')}})}
function count(){main.innerHTML=`<section class="screen">${head('Number Safari 1–100','Quantity • sequence • comparison • patterns')}<div class="game-area"><div class="objective">🔢 Stable counting 1–100, one-to-one correspondence, more/less, before/after and pattern thinking.</div><div class="num-grid">${Array.from({length:100},(_,i)=>`<button class="num-btn" data-n="${i+1}">${i+1}<small>tap</small></button>`).join('')}</div><div class="count-stage"><div id="cp" class="prompt">कोई number चुनो</div><div id="ci" class="count-items"></div><div id="cf" class="feedback"></div></div></div></section>`;bindBack();document.querySelectorAll('.num-btn').forEach(b=>b.onclick=()=>{const n=+b.dataset.n;sfx('count');$('#cp').innerHTML=`${n}<br><small>Count ${n} objects</small>`;const shown=Math.min(n,30);$('#ci').innerHTML=Array.from({length:shown},(_,i)=>`<span class="object">${['🍎','⭐','🎈','🧸','🌸'][i%5]}</span>`).join('')+(n>30?`<p class="sub">+ ${n-30} more — groups of 10 में सोचो।</p>`:'');const q=Math.min(99,Math.max(1,n));$('#cf').innerHTML=`<button class="secondary" id="hear">🔊 ${n}</button> <button class="primary" id="challenge">🎯 Challenge</button>`;$('#hear').onclick=()=>speak(String(n));$('#challenge').onclick=()=>qGame('count','Safari Challenge','Before / after',`${q} के बाद कौन आता है?`,[String(Math.max(1,q-1)),String(q),String(Math.min(100,q+1)),String(Math.min(100,q+2))],2,'Number sequence और flexible thinking.','count')})}
function story(){qGame('story','Mystery Mansion','Safe spooky-fun story','दरवाज़े के बाहर घंटी बजी। सबसे अच्छा पहला step क्या है?',['दरवाज़ा अकेले खोलना','किसी trusted adult को बुलाना','अँधेरे में भागना','सब lights बंद करना'],1,'Prediction, safety, communication और decision making.','horror')}
function prank(){qGame('prank','Prank Detective','Funny but kind','दोस्त का मज़ाक करना है। कौन-सा prank kind है?',['उसकी चीज़ छिपा देना','डराकर रुलाना','funny sticker challenge पूछना','उसकी drawing फाड़ना'],2,'Humour + empathy + consent-aware social choices.','pop')}
function family(){qGame('family','Family Vlog Day','Everyday sequence','Breakfast से पहले routine में क्या करना useful है?',['हाथ धोना','खिलौने छिपाना','lights off करना','भागना'],0,'Self-care, routine sequencing और responsibility.','tap')}
function memory(){qGame('memory','Memory Snap','Look → remember → choose','अभी कौन-सा pair साथ था?',['🍎⭐','🎈🧸','🌸🍎','⭐🎈'],1,'Working memory, attention और visual recall.','magic')}
function sort(){qGame('sort','Toy Sorting Challenge','Think → group → explain','कौन-सी चीज़ round है?',['📘','⚽','🧱','📏'],1,'Classification, attributes और reasoning language.','tap')}
function sequence(){qGame('sequence','Story Sequence','What comes next?','बीज → पौधा → फूल → ?',['फल','जूता','चम्मच','बादल'],0,'Logical sequencing and prediction.','magic')}
function nature(){qGame('nature','Nature Explorer','Observe the world','किसे पानी की ज़रूरत होती है?',['पत्थर','पौधा','कुर्सी','किताब'],1,'Observation, living/non-living and care.','tap')}
function feelings(){qGame('feelings','Friendship Choices','Feel → understand → act','दोस्त उदास है। helpful choice?',['हँसो','सुनो और पूछो “क्या हुआ?”','उसे ignore करो','उसका खिलौना ले लो'],1,'Empathy, communication and cooperation.','magic')}
function market(){qGame('market','Mini Family Market','Real-life maths','तुम्हारे पास 3 apples हैं और 2 और मिले। कितने?',['4','5','6','7'],1,'Addition through meaningful quantity.','count')}
function sound(){qGame('sound','Sound Detective','Listen and connect','🐶 की आवाज़ किसकी हो सकती है?',['Cat','Dog','Cow','Bird'],1,'Auditory discrimination and vocabulary.','tap')}
function music(){main.innerHTML=`<section class="screen">${head('Birthday Beat Party','Happy birthday • rhythm • rhyme • movement')}<div class="game-area"><div class="objective">🎵 Rhythm, beat, listening, memory, creative expression and gross-motor movement.</div><div class="music-pad">${['🎂','⭐','👏','🎵','🪇','🎈','🥁','💃'].map((x,i)=>`<button class="pad" data-i="${i}">${x}<br><small>${i+1}</small></button>`).join('')}</div><div class="dance"><div><div id="dc" class="dance-character">💃</div><p id="df" class="prompt">Beat पर tap करो!</p><button class="primary" id="danceBtn">🎶 Start Dance</button></div></div></div></section>`;bindBack();document.querySelectorAll('.pad').forEach(b=>b.onclick=()=>{sfx('dance');speak(['birthday','star','clap','music','shake','balloon','drum','dance'][+b.dataset.i]);});$('#danceBtn').onclick=()=>{$('#dc').classList.toggle('active');sfx('dance');$('#df').textContent='1… 2… 3… Move! 💃';reward('music')}}
function rhymes(){qGame('rhymes','Rhyme & Action','Sound play + movement','Which word rhymes with “cat”?',['sun','hat','dog','tree'],1,'Phonological awareness + vocabulary + action.','dance')}
function craft(){main.innerHTML=`<section class="screen">${head('DIY Drawing Studio','Fine motor • creativity • shapes • letters')}<div class="game-area"><div class="objective">🎨 Trace, draw, plan, create and describe — fine-motor control + creativity + communication.</div><div class="craft-board"><div class="craft-card" id="trace"><div class="big">✏️</div><h2>Letter Trace</h2><p>A, B, C या अ, आ, इ को उंगली से हवा में trace करो.</p><button class="primary">Start Trace</button></div><div class="craft-card" id="draw"><div class="big">🖍️</div><h2>Free Drawing</h2><p>एक birthday scene, funny family या mystery house बनाओ.</p><button class="primary">Create</button></div></div></div></section>`;bindBack();$('#trace').onclick=()=>{sfx('craft');qGame('craft','Trace Mission','Fine motor play','किसे trace करना है?',['A','B','अ','⭐'],0,'Pre-writing control and letter familiarity.','craft')};$('#draw').onclick=()=>{sfx('craft');toast('🎨 Imagine → draw → describe!');reward('craft')}}
function body(){qGame('body','Move Like a Character','Gross motor + direction','Laddu character को jump करना है। पहले क्या check करें?',['Safe open space','Wet floor','Stairs','Sharp objects'],0,'Body awareness, safety, balance and self-management.','whoosh')}
function open(){qGame('open','Free Play Studio','Choose, combine, create','आज कौन-सा mix सबसे creative है?',['Story + drawing + music','Only one button','No imagination','Skip everything'],0,'Choice, initiative, creativity and self-directed learning.','magic')}
function playPath(){const picks=['abc','hindi','count','story','craft','music'];launch(picks[state.done%picks.length])}
$('#langBtn').onclick=()=>{sfx('tap');toast('Hindi + English learning world')};$('#soundBtn').onclick=()=>{state.sound=!state.sound;save();$('#soundBtn').innerHTML=state.sound?'🔊 <span>Sound On</span>':'🔇 <span>Sound Off</span>';if(state.sound)sfx('magic')};
home();